### ISSUE TITLE
Can't login Zalo

### ISSUE THREAD

**Issue by ddcuongit** [SanbiVN/ZaloExcel#1]
Hi bạn ơi,
Cho mình hỏi xíu, hiện tại mình bấm đăng nhập thì báo lỗi như hình dưới:

![image](https://user-images.githubusercontent.com/89700067/229703659-c63a98a0-03c7-4b88-bc8e-cb26f85f79d6.png)

![image](https://user-images.githubusercontent.com/89700067/229703721-6585148a-f3cc-4f09-9ccf-51ff9684ce19.png)

**Comment by SanbiVN** [comment]
Mình đang cập nhật bản mới, đã sửa lỗi đó, nhưng chưa update lên github.
